# Generated by Django 4.1.7 on 2023-04-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_animal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='user',
            new_name='uploaded_by',
        ),
    ]
