# Generated by Django 4.1.7 on 2023-04-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_user_animal_uploaded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='uploaded_by',
            new_name='user',
        ),
    ]
